// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://geutkqzkkiajzzzmspum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdldXRrcXpra2lhanp6em1zcHVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2OTAyOTIsImV4cCI6MjA1ODI2NjI5Mn0.Ea9IPjIHaZjwi4nYZ47fqLJVS5sa_SjrxMp0lkged1s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);